import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"
import ReactQueryProvider from "./queryProvider";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { GoogleOAuthProvider } from "@react-oauth/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TutorMe - where exceptional tutors teachp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
          <script
          async
          src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5597598848182147`}
          crossOrigin="anonymous"
        ></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || "949950176019-9sf5271jp00lq2bgqjr3ngarqhrigc0i.apps.googleusercontent.com"}>
          <ReactQueryProvider>{children}</ReactQueryProvider>

          <Toaster
            position="top-center"
            richColors
            closeButton
            expand
            toastOptions={{
              duration: 2600,
              className: "shadow-xl rounded-2xl border border-slate-200 bg-white/90 backdrop-blur-md text-slate-900 px-4 py-3",
              style: { fontWeight: 600 },
            }}
          />
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
