import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import ReactQueryProvider from './queryProvider'
import { Toaster } from 'react-hot-toast'
import { ThemeProvider } from '@/components/ui/theme-provider'
import { GoogleOAuthProvider } from "@react-oauth/google";

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'TutorMe - where exceptional tutors teachp',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
           <GoogleOAuthProvider clientId="YOUR_GOOGLE_CLIENT_ID">
        <ReactQueryProvider>{children}</ReactQueryProvider>
      
        <Toaster/>
        </GoogleOAuthProvider>
      </body>
    </html>
  )
}
